src/Entity/Booking.php
<?php

namespace App\Entity;

use ApiPlatform\Core\Annotation\ApiResource;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Serializer\Annotation\Groups;

/**
 * @ORM\Entity(repositoryClass="App\Repository\BookingRepository")
 * @ApiResource()
 * @UniqueEntity(fields={"hour_start","room_id"}, message="Il existe déjà une réservation pour cette salle à cette horaire !")
 * @ORM\HasLifecycleCallbacks()
 */
class Booking
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     * @Groups({"todayBooking","userBooking"})
     */
    private $id;

    /**
     * @ORM\Column(type="datetime")
     * @Groups({"todayBooking","userBooking"})
     */
    private $bookingDate;

    /**
     * @ORM\Column(type="datetime")
     * @Groups({"todayBooking","userBooking"})
     */
    private $dateStart;

    /**
     * @ORM\Column(type="time", nullable=true)
     * @Groups({"todayBooking","userBooking"})
     */
    private $HourStart;

    /**
     * @var string
     * @ORM\Column(type="string")
     * @Groups({"todayBooking","userBooking"})
     */
    private $status;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Room", inversedBy="bookings")
     * @ORM\JoinColumn(nullable=true)
     * @Groups({"todayBooking","userBooking"})
     */
    private $room;


    /**
     * @var integer
     * @ORM\Column(type="integer",name="duration")
     * @Groups({"todayBooking","userBooking"})
     */
    private $duration;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="waitinglistuser")
     * @ORM\JoinColumn(name="userwaitinglist",nullable=true)
     */
    private $userwaitinglist;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="booking")
     * @ORM\JoinColumn(nullable=true)
     * @Groups({"todayBooking","userBooking"})
     */
    private $user;

    /**
     * @var string
     * @ORM\Column(type="string",name="rate", nullable=true)
     */
    private $rate;


    public function __construct()
    {
        $this->status = "room_available";
        $this->bookingDate = new \DateTime();
        $this->bookingDate->setTime(00, 00, 00);
    }


    public function getId(): ?int
    {
        return $this->id;
    }

    public function getBookingDate(): ?\DateTime
    {
        return $this->bookingDate;
    }

    public function setBookingDate(\DateTime $bookingDate): self
    {
        $this->bookingDate = $bookingDate;

        return $this;
    }

    public function getDateStart(): ?\DateTime
    {
        return $this->dateStart;
    }

    public function setDateStart(\DateTime $dateStart): self
    {
        $this->dateStart = $dateStart;

        return $this;
    }


    public function getRoom(): ?Room
    {
        return $this->room;
    }

    public function setRoom(?Room $room): self
    {
        $this->room = $room;

        return $this;
    }

    public function getHourStart(): ?\DateTimeInterface
    {
        return $this->HourStart;
    }

    public function setHourStart(\DateTimeInterface $HourStart): self
    {
        $this->HourStart = $HourStart;

        return $this;
    }


    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    /**
     * @return int
     */
    public function getDuration(): int
    {
        return $this->duration;
    }

    /**
     * @param int $duration
     */
    public function setDuration(int $duration): void
    {
        $this->duration = $duration;
    }

    /**
     * @return string
     */
    public function getStatus(): string
    {
        return $this->status;
    }

    /**
     * @param string $status
     * @return Booking
     */
    public function setStatus(string $status): Booking
    {
        $this->status = $status;
        return $this;
    }

    /**
     * @return string
     */
    public function getRate()
    {
        return $this->rate;
    }

    /**
     * @param string $rate
     * @return Booking
     */
    public function setRate(string $rate) :self
    {
        $this->rate = $rate;
        return $this;
    }
    /**
     * @return mixed
     */
    public function getUserwaitinglist()
    {
        return $this->userwaitinglist;
    }

    /**
     * @param mixed $userwaitinglist
     * @return Booking
     */
    public function setUserwaitinglist(?User $userwaitinglist)
    {
        $this->userwaitinglist = $userwaitinglist;
        return $this;
    }




}

src/Form/UserType.php
<?php

namespace App\Form;

use App\Entity\User;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\EmailType;
use Symfony\Component\Form\Extension\Core\Type\PasswordType;
use Symfony\Component\Form\Extension\Core\Type\RepeatedType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class UserType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('lastname',TextType::class,[
                'label'=> 'Nom'
            ])
            ->add('firstname',TextType::class,[
                'label' => 'Prénom'
            ])
            ->add('email',EmailType::class,[
                'label' =>'Email'
            ])
            ->add('plainPassword',RepeatedType::class,
                [
                    'type' => PasswordType::class,
                    'first_options' => [
                        'label' => 'Mot de passe'
                    ],
                    'second_options' =>[
                        'label' => 'Répéter le mot de passe'
                    ],
                    'invalid_message' => 'les mots de passe ne sont pas identiques !'
                ])
            ->add('roles',ChoiceType::class,
                [
                    'placeholder' => 'Séléctionnez un statut',
                'required' => true,
                    'multiple' => true,
                    'choices' => [
                        'ADMINISTRATEUR' => 'ROLE_ADMIN',
                        'UTILISATEUR' => 'ROLE_USER',
                        'VISITEUR' => 'ROLE_VISITOR'
                    ]
            ])

        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => User::class,
            'csrf_protection'   => false
        ]);
    }
}

src/Controller/UserController.php
<?php

namespace App\Controller;


use App\Entity\Booking;
use App\Entity\User;
use App\Repository\BookingRepository;
use App\Repository\UserRepository;
use App\Services\Booking\BookingWorkflowHandler;
use App\Services\Booking\cleaningBooking;
use Doctrine\Common\Persistence\ObjectManager;
use Doctrine\ORM\NonUniqueResultException as NonUniqueResultExceptionAlias;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Core\Security;
use Symfony\Component\Security\Http\Authentication\AuthenticationUtils;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Workflow\Exception\LogicException;

class UserController extends AbstractController
{
    private $security;

    public function __construct(Security $security)
    {
        $this->security = $security;
    }

    /**
     * @Route("/user", name="user")
     */
    public function index()
    {
        return $this->render('user/index.html.twig', [
            'controller_name' => 'UserController',
        ]);
    }

    /**
     * @Route("/login", name="login")
     * @param AuthenticationUtils $authenticationUtils
     * @return Response
     */
    public function login(AuthenticationUtils $authenticationUtils)
    {

        $error = $authenticationUtils->getLastAuthenticationError();
        $lastUsername = $authenticationUtils->getLastUsername();



        return $this->render('user/login.html.twig',[

            'last_username' => $lastUsername,
            'error' => $error
        ]);
    }

    /**
     * @Route("/deconnexion" ,name="logout")
     */
    public function logout(){}


    /**
     * @Route("/userBooking/{id}/{deleted}", defaults={"deleted" : null}, name="user_booking")
     * @param User $user
     * @param $deleted
     * @param cleaningBooking $cb
     * @param ObjectManager $manager
     * @param UserRepository $userRepository
     * @return Response
     * @throws NonUniqueResultExceptionAlias
     */
    public function userBooking(
        User $user,
        $deleted,
        cleaningBooking $cb,
        ObjectManager $manager,
        UserRepository $userRepository)
    {

        # Permet d'épurer la base de données des réservation passée
        $cb->clean($manager);


        if (!empty($deleted) and $deleted == false)
        {
            $this->addFlash('success', "La réservation est enregistrée un mail de confirmation vous a été envoyé");
        }

        $liste = $user->getBooking();



        if ($this->security->isGranted('ROLE_VISITOR_ADMIN')) {

            $status = 'admin_visitor';

            $otherBooker =true;
            /* $bookers ??  */
            $firstnameAsked = 'Visitor';
            $userMail = $user->getEmail();

            $bookers = $userRepository->findBy([
                'email' => $userMail,
                'firstname' => $firstnameAsked
            ],null);


            return $this->render('user/user_booking.html.twig',[
                'status' => $status,
                'liste' => $liste,
                'user_booking' => $user,
                'other_booker' => $otherBooker,
                'visitor_admin' => $user,
                'bookers' => $bookers
            ]);

        } elseif ($this->security->isGranted('ROLE_VISITOR')) {

            $status = 'booker_visitor';
            $idVisitor = $user->getId();

            $emailVisitor = $user->getEmail();
            $firstnameVisitor = $user->getFirstname();

            $otherBooker = $userRepository->findOtherVisitor($idVisitor,$emailVisitor,$firstnameVisitor);

            $adminVisitor = $userRepository->findOneBy([
                'firstname' => 'Visitor_admin',
                'email' => $emailVisitor
            ],null);


            $stat = true;
        } else {
            $otherBooker = null;
            $adminVisitor = null;
            $status = null;
            $stat = false;
        }


        return $this->render(
            'user/user_booking.html.twig',
            [
                'status' => $status,
                'liste' => $liste,
                'user_booking' => $user,
                'other_booker' => $otherBooker,
                'visitor_admin' => $adminVisitor

            ]
        );
    }

    /**
     * @Route("/viewHistory/{id}/{bookingid}",defaults={"bookingid": null },name="user_bookings_history")
     * @param User $user
     * @param $bookingid
     * @param BookingRepository $repoBooking
     * @return Response
     */
    public function bookingsInHistory(User $user,$bookingid,BookingRepository $repoBooking)
    {
        if (null != $bookingid) {

            $bookingForRate = $repoBooking->find($bookingid);

            return $this->render('user/view_bookings_history.html.twig',[
                'id' => $user->getId(),
                'bid' => $bookingForRate
            ]);
        }

        return $this->render('user/view_bookings_history.html.twig',[
            'user_booking' =>$user
        ]);
    }

    /**
     * Get the vote from history
     * @Route("/checkRate",name="booking_rate")
     * @param Request $request
     * @param BookingRepository $bookingRepository
     * @param ObjectManager $manager
     * @return RedirectResponse
     */
    public function checkRateForBooking(Request $request,BookingRepository $bookingRepository,ObjectManager $manager)
    {

        $idbooking = $request->request->get('idb');
        $historyBooking = $bookingRepository->find($idbooking);
        $userid = $this->getUser()->getId();
        $rating = $request->request->get('rating');

        #check if vote has ever made
        if (null == $historyBooking->getRate()) {

            $historyBooking->setRate($rating);
            $manager->flush();
            $this->addFlash('success', "Merci, votre vote est enregistré");
        } else {
            $this->addFlash('warning', "Vous avez déjà voté !");
        }

        return $this->redirectToRoute('user_bookings_history',['id' => $userid]);
    }

    /**
     * @Route("/abortWaitingList/{status}/{id}", name="wl_aborted")
     * @param string $status
     * @param Booking $booking
     * @param BookingWorkflowHandler $bwh
     * @param ObjectManager $manager
     * @return RedirectResponse
     */
    public function abortWaitingList($status,Booking $booking, BookingWorkflowHandler $bwh,ObjectManager $manager)
    {
        try {

           $bwh->handle($booking,$status);
           $booking->setUserwaitinglist(null);
           $manager->flush($booking);

           $this->addFlash('success', "La liste d'attente est bien abandonnée.");

        } catch (LogicException $e) {
            $this->addFlash('error', "Impossible d'annuler la liste d'attente");
        }

        $userId = $this->getUser()->getId();
        $deleted = false;

        return $this->redirectToRoute('user_booking',[
            'id'=>$userId,
            'deleted' =>$deleted
        ]);
    }

    /**
     * @param BookingWorkflowHandler $bwh
     * @param ObjectManager $manager
     * @param Booking $booking
     * @param $admin
     * @param $status
     * @return RedirectResponse
     * @Route("/deleteUserBooking/{id}/{status}/{admin}",defaults={"admin" : null },requirements={"admin" : "\d+" }, name="delete_user_booking")
     */
    public function deleteUserBooking(BookingWorkflowHandler $bwh,ObjectManager $manager, Booking $booking,$admin,$status)
    {
        $user = $this->getUser();

        try {
            $bwh->handle($booking,$status);

                if (null == $booking->getId()) {
                    $this->addFlash('success',"Votre réservation à été annulée, \n le créneau est désormais disponible. ");

                }else {

                    $content_status = $booking->getStatus();
                    if ($content_status == 'room_has_been_confirmed') {
                        $this->addFlash('success', "Votre réservation à été annulée, \n une personne a pu en bénéficier. ");
                        $manager->flush($booking);
                    }
                }


        } catch (LogicException $e) {
            $this->addFlash('error',"La réservation ne peut être annulée");
        }
        $deleted = true;

        // If delete user booking come from admin
        if (!null == $admin) {
            $lastNameUser = $booking->getUser()->getLastname();
            $firstNameUser = $booking->getUser()->getFirstname();
            $this->addFlash('success',"La réservation de $firstNameUser $lastNameUser à bien été supprimée");
            return $this->redirectToRoute('admin_edit_user',[

            ]);
        }

        return $this->redirectToRoute('user_booking', [
            'id'=> $user->getId(),
            'deleted' =>$deleted

        ]);

    }

}

templates/user/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello UserController!{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

<div class="example-wrapper">
    <h1>Hello {{ controller_name }}! ✅</h1>

    This friendly message is coming from:
    <ul>
        <li>Your controller at <code><a href="{{ 'C:/Users/sebvr/Desktop/Projets/EasyBoardRoom/easyboardroom/src/Controller/UserController.php'|file_link(0) }}">src/Controller/UserController.php</a></code></li>
        <li>Your template at <code><a href="{{ 'C:/Users/sebvr/Desktop/Projets/EasyBoardRoom/easyboardroom/templates/user/index.html.twig'|file_link(0) }}">templates/user/index.html.twig</a></code></li>
    </ul>
</div>
{% endblock %}

templates/user/user_booking.html.twig
{% extends 'layout2.html.twig' %}

{% block title %}Vos réservations{% endblock %}
{% block stylesheets %}{{ parent() }} {% endblock %}

{% block body %}
    {{ parent() }}

    {% set status_waiting = 'room_in_waiting_list' %}
    {% set status_history = 'room_has_been_booked' %}

    {% if liste|length == 0  %}
        <h3>
            <p class="text-center">Aucune réservation</p>
        </h3>
        <div class="text-center">
        <a href="{{ path('booking_create') }}" class="btn btn-outline-dark">Nouvelle réservation</a>
        </div>
            {% else %}
        {% if is_granted('ROLE_VISITOR_ADMIN') %}
            <h3 class="text-center text-warning">
                Réservations de <strong>{{ user_booking.firstname }} {{ user_booking.lastname }}</strong>
            </h3>
        {% else %}
            <h3 class="text-center">
                Réservations de <strong>{{ user_booking.firstname }} {{ user_booking.lastname }}</strong>
                </h3>
        {% endif %}
    {% endif %}

    {% if getHistoryList(app.user,status_history)|length > 0 %}
        {% set nb_booking_in_history = getHistoryList(app.user,status_history)|length %}
        <div class="text-center">
            <a href="{{ path('user_bookings_history',{'id': app.user.id }) }}" type="button" class="btn btn-info mb-3" data-toggle="tooltip" data-placement="bottom" title="Voir mes réservation passée">
                Historique <span class="badge badge-light">{{ nb_booking_in_history }}</span>
            </a>
        </div>
    {% else %}

        <p class="text-center"><cite>(pas d'historique)</cite></p>

    {% endif %}

    {% if other_booker is not null %}
        <div class="card text-center mb-5">
            <h4 class="card-header">
                <strong>
                    Panneau de contrôle <img src="{{ asset('images/icons/visibility.png') }}" id="oeil"/>
                </strong>
            </h4>
            <div class="card-body mb-3" id="panneau-control">
                <h5 class="card-title">
                    Changer de statut
                </h5>

                {%  if status == 'booker_visitor' %}
                     <a class="btn btn-primary mt-2" href="{{ path('change_status',{'id': user_booking.id,'idvisitorasked': other_booker.id}) }}">Utilisateur<br>{{ other_booker.firstname }} {{ other_booker.lastname }}</a>
                    <a class="btn btn-warning mt-2" href="{{ path('change_status',{'id': user_booking.id,'idvisitorasked': visitor_admin.id}) }}">Administrateur<br>{{ visitor_admin.firstname }} {{ visitor_admin.lastname }}</a>

                {% endif %}
                {% if status == 'admin_visitor' %}
                    {% for booker in bookers %}
                <a class="btn btn-primary mt-2" href="{{ path('change_status',{'id' :user_booking.id,'idvisitorasked': booker.id}) }}">Utilisateur<br>{{ booker.firstname }} {{ booker.lastname }}</a>
                    {% endfor %}
                    <br>
                    <a href="{{ path('panel_admin',{'id':user_booking.id}) }}" class="btn btn-warning mt-3">Gestion</a>
                {% endif %}
            </div>
        </div>
    {% endif %}

    <br>
    {% if liste|length > 0  %}
        {% if getWaitingList(app.user,status_waiting) %}
            {% set wl = getWaitingList(app.user,status_waiting) %}
            {% set number_of_waiting_list = wl|length %}
        {% endif %}

       <table class="table table-striped shadow-lg p-3 mb-auto bg-white rounded">
           <thead class="thead-light">
           <tr class="bg-light">
               <td colspan="7" class="text-center">
                   <a href="{{ path('booking_create') }}" class="btn btn-outline-success">Nouvelle reservation</a>
               </td>

           </tr>
                <tr>
                    <th scope="col" width="12%">Salle</th>
                    <th scope="col" width="12%">Réservation effectuée le:</th>
                    <th scope="col" width="12%">Date de la réservation</th>
                    <th scope="col" width="10%">Heure de début de la réservation</th>
                    <th scope="col" width="5%">Durée de la réservation</th>
                    <th scope="col" width="19%">Statut</th>
                    <th scope="col" width="13%">Supression</th>
                </tr>
           </thead>
           <tbody>
            {% for booking in liste %}
                {% if booking.status != 'room_has_been_booked' %}
                    <tr>
                        <td>{{ booking.room.name }}</td>
                        <td>{{ booking.bookingDate | date('d-m-Y') }}</td>
                        <td>{{ booking.dateStart | date('d-m-Y') }}</td>
                        <td>{{ booking.hourStart | date('H:i') }}</td>
                        <td>{{ booking.duration }} h</td>
                        {% if booking.status == 'room_booked' %}
                            <td>Confirmée</td>
                        {% elseif booking.status == 'room_in_waiting_list' %}
                            <td>Confirmée<br>

                               <strong><cite>(1 pers. en liste d'attente)</cite></strong>
                            </td>
                        {% elseif booking.status == 'room_has_been_confirmed' %}
                            <td>

                                <strong>Liste d'attente débloquée,<br>réservation confirmée !</strong>

                            </td>
                        {% endif %}

                        <td>
                           {% if booking.status != 'room_has_been_booked' %}
                                {% if is_granted('ROLE_ADMIN') %}
                                    <a href="{{ path('delete_user_booking', {
                                        'id': booking.id,
                                        'admin' : 1,
                                        'status' : 'booking_deleted'

                                    }) }}"
                                       class="btn btn-danger">
                                        Supprimer
                                    </a>
                                {% else %}
                                <a href="{{ path('delete_user_booking', {
                                    'id': booking.id,
                                    'status' : 'booking_deleted'
                                }) }}"
                                   class="btn btn-danger">
                                    Supprimer
                                </a>
                                {% endif %}
                           {% endif %}
                        </td>
                    </tr>
                {% endif %}
            {% endfor %}
            {% if wl is defined and  number_of_waiting_list is defined %}

                {% if number_of_waiting_list > 0 %}
                   {% for booking_awaiting in wl %}
                        <tr class="bg-warning">
                            <td>{{ booking_awaiting.room.name }}</td>
                            <td>{{ booking_awaiting.bookingDate | date('d-m-Y') }}</td>
                            <td>{{ booking_awaiting.dateStart | date('d-m-Y') }}</td>
                            <td>{{ booking_awaiting.hourStart | date('H:i') }}</td>
                            <td>{{ booking_awaiting.duration }} h</td>
                            {% if booking_awaiting.status == 'room_in_waiting_list' %}
                                <td><strong>En liste d'attente</strong></td>
                            {% endif %}
                            <td>
                                <a href="{{ path('wl_aborted',{
                                    'status' : 'room_booked',
                                    'id' : booking_awaiting.id
                                }) }}" class="btn btn-primary">Se désister</a>
                            </td>

                        </tr>
                   {% endfor %}
                {% endif %}
           {% endif %}
           </tbody>
        </table>
    {% endif %}
    <div class="text-right mb-3">
        {% if is_granted('ROLE_ADMIN') %}
         <a href="{{ path('admin_edit_user') }}" class="btn btn-outline-secondary">Retour</a>
        {% endif %}
    </div>




{% endblock %}

templates/user/view_bookings_history.html.twig
{% extends 'layout2.html.twig' %}

{% block title %}
Vos réservations passées
{% endblock %}
{% block body %}
    {{ parent() }}

    {% set status_history = 'room_has_been_booked' %}
    {% set history = getHistoryList(app.user,status_history) %}

    {% if bid is defined %}
        <table class="table table-bordered table-striped shadow-lg p-3 mb-5 bg-dark rounded text-center">
            <thead class="thead-light">
                <tr class="text-center">
                    <td>
                        <div class="card text-center" >
                            <div class="card-header">
                                <h4>
                                    Vos impressions concernant votre location du {{ bid.dateStart|date('d/m/Y') }} à {{ bid.hourStart|date('H:i') }}
                                    <br>
                                     Nom de l'espace : {{ bid.room.name }}
                                </h4>
                            </div>
                            <img class="card-img-top" src="{{ asset('images/room/' ~ bid.room.image.name) }}" width="50%">
                            <div class="card-body">
                                <h5 class="card-title">Notez la prestation</h5>
                                <form method="post" action="{{ path('booking_rate') }}">
                                    <input type="hidden" name="idb" value="{{ bid.id }}">
                                <p class="card-text">
                                    {% include 'user/rate_room_svg.html.twig' %}
                                </p>
                                <button type="submit" class="btn btn-primary">Vote !</button>
                                </form>
                            </div>
                        </div>
                    </td>
                </tr>
            </thead>
        </table>
    {% endif %}

    <table class="table table-bordered table-striped shadow-lg p-3 mb-5 bg-dark rounded">
        <thead class="thead-light">
        <tr>
            <td colspan="6" class="bg-light text-center">
                <h4 class="font-weight-bolder">HISTORIQUE DES RESERVATIONS</h4>
                <a href="{{ path('user_booking',{'id': app.user.id}) }}" class="btn btn-outline-dark">Retour</a>
            </td>
        </tr>
        </thead>
        <thead class="thead-dark">
            <tr>
                <th scope="col" width="12%">Salle</th>
                <th scope="col" width="12%">Réservation effectuée le:</th>
                <th scope="col" width="12%">Date de la réservation</th>
                <th scope="col" width="10%">Heure de début de la réservation</th>
                <th scope="col" width="5%">Durée de la réservation</th>
                <th scope="col" width="15%" class="text-center">Vote</th>
            </tr>

        </thead>
        <tbody class="bg-light">
        {% for booking in history %}
            <tr>
                <td>{{ booking.room.name }}</td>
                <td>{{ booking.bookingDate | date('d-m-Y') }}</td>
                <td>{{ booking.dateStart | date('d-m-Y') }}</td>
                <td>{{ booking.hourStart | date('H:i') }}</td>
                <td>{{ booking.duration }} h</td>
                {% if booking.rate is null %}


                    <td class="text-center">

                        <a href="{{ path('user_bookings_history',{'id': app.user.id,'bookingid': booking.id}) }}" class="btn btn-outline-success btn-sm"  >
                            Votez
                        </a>

                    </td>
                {% else %}
                    <td class="text-center">
                    <img src="{{ asset('images/rate/stars_'~ booking.rate~'.png') }}" width="50%">

                {% endif %}
            </tr>

        {% endfor %}
        </tbody>

    </table>






{% endblock %}